# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b3e90b108dca584c2cc3e19f383829b1aff064ed6d367ee3341724c1a7b0ce9fab10c8b3d06f2ee68a8400d73dff5557353aec6e23593578bed01fa23c935d

test:
  secret_key_base: 768b03e740446c3440c20ef9e3a0d6b36ed77f2cb3472f83925e999e8f8574d454b9d5d5e2a1602a93bd0c58baab497ca0fbc5454916a82e1201346f1585eff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
